
const fakeData = [
    {
      "id":1,
      "name":"Shakib Al-hasan",
      "born":"Mar 24, 1987",
      "age":33,
      "img":"https://www.crictracker.com/wp-content/uploads/2019/09/Shakib-Al-Hasan.jpg",
      "country":"Bangladesh",
      "role":"Batting Allrounder",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":33,
      "odi":24,
      "t20":51,
      "salary":425000
    },
    {
      "id":2,
      "name":"Taskin Ahmed",
      "born":"Mar 04, 1995",
      "age":25,
      "img":"https://www.mykhel.com/thumb/247x100x233/cricket/players/3/5563.jpg",
      "country":"Bangladesh",
      "role":"Bowler",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":10,
      "odi":5,
      "t20":10,
      "salary":45000
    },
    {
      "id":3,
      "name":"Mosaddek Hossain",
      "born":"Dec 10, 1995",
      "age":25,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c170909/mosaddek-hossain.jpg",
      "country":"Bangladesh",
      "role":"Bowler",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":5,
      "odi":5,
      "t20":12,
      "salary":40000
    },
    {
      "id":4,
      "name":" Mashrafe Mortaza",
      "born":"Oct 05, 1983",
      "age":37,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c170920/mashrafe-mortaza.jpg",
      "country":"Bangladesh",
      "role":"Batsman",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":20,
      "odi":45,
      "t20":15,
      "salary":550000
    },
    {
      "id":5,
      "name":" Mustafizur Rahman",
      "born":"Sep 06, 1995",
      "age":25,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c170925/mustafizur-rahman.jpg",
      "country":"Bangladesh",
      "role":"Batsman",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":25,
      "odi":40,
      "t20":13,
      "salary":150000
    },
    {
      "id":6,
      "name":" Mushfiqur Rahim",
      "born":"Jun 09, 1987",
      "age":33,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c170916/mushfiqur-rahim.jpg",
      "country":"Bangladesh",
      "role":"Batsman",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":21,
      "odi":16,
      "t20":13,
      "salary":160000
    },
    {
      "id":7,
      "name":" Nasir Jamal",
      "born":"Dec 21, 1993",
      "age":33,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c178325/nasir-jamal.jpg",
      "country":"Afghanistan",
      "role":"Batsman",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":22,
      "odi":17,
      "t20":14,
      "salary":120000
    },
    {
      "id":8,
      "name":" Rashid Khan",
      "born":"Dec 21, 1991",
      "age":35,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c170857/rashid-khan.jpg",
      "country":"Afghanistan",
      "role":"Bowler",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":27,
      "odi":13,
      "t20":19,
      "salary":10000
    },
    {
      "id":9,
      "name":" Shahid Afridi",
      "born":"Mar 01, 1980",
      "age":40,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c146389/shahid-afridi.jpg",
      "country":"Pakisthan",
      "role":"Batsman",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":30,
      "odi":22,
      "t20":25,
      "salary":170000
    },
    {
      "id":10,
      "name":"  Rohit Sharma",
      "born":"Apr 30, 1987 ",
      "age":34,
      "img":"https://www.cricbuzz.com/a/img/v1/152x152/i1/c170658/rohit-sharma.jpg",
      "country":"India",
      "role":"Batsman",
      "BattingStyle":"Left Handed Bat",
      "BowlingStyle":"Left-arm orthodox",
      "test":31,
      "odi":33,
      "t20":34,
      "salary":180000
    },
     
  ]; 

  export default fakeData;
